### ISSUE TITLE
[QUESTION] - Minetrack & Hypixel API

### ISSUE THREAD

**Issue by TheMystery** [Cryptkeeper/Minetrack#204]
Hey there, 
So I was looking at the Minetrack site and messing around with the Hypixel API and found there was an endpoint that displayed all the gamemode's  playercounts. 
I was wondering if anyone knew of a way to intergrate the Hypixel API with Minetrack to show every gamemode's playercount. 

For example: 
Script calls the Hypixel API endpoint which returns a JSON list of each gamemode and their playercounts
Minetrack plots each gamemode as if they were different servers.

If not I might try mess around with the code but really I can't tell what files are making the calls and stuff.

**Comment by hugmanrique** [comment]
It's unofficial, but Connor Linfoot made https://hytrack.me/

**Comment by TheMystery** [comment]
Looking at it I'm guessing he created his own systems (that works like minetrack) to work with their api. Might try and see if I can get in contact with him (Although unlikely) and see if he can lend a hand. 
(If someone does work out a way would be great but I'll see what I can do)

**Comment by hugmanrique** [comment]
If you're doing this for learning purposes, I can point you to the files you will need to modify:
- https://github.com/Cryptkeeper/Minetrack/blob/master/lib/ping.js to periodically ping the Hypixel API and return cached counts from the `ping` method depending on "invalid game IPs" you set on the `config.json` file or directly retrieve from the API.
- https://github.com/Cryptkeeper/Minetrack/blob/6ce1697a3955a3b249a63c26abf4f3aba581f69e/lib/server.js#L53 to modify the sent favicons for each gamemode.
- https://github.com/Cryptkeeper/Minetrack/blob/6ce1697a3955a3b249a63c26abf4f3aba581f69e/assets/js/servers.js#L276 to modify the displayed data (e.g. remove supported versions and protocols).

Otherwise, I think you would be reinventing the wheel, especially when a Hypixel admin already has their own tracker.

**Comment by TheMystery** [comment]
Thank you. Also I in no way want to recreate Connor's tool. It looks amazing and he seems to be putting in a great amount of work to improve and make it better.
