### ISSUE TITLE
High Availability/Load Balancing?

### ISSUE THREAD

**Issue by LeviDevs** [Cryptkeeper/Minetrack#206]
I was wondering if Minetrack supports high availability via load balancing. I know there's a servers.json file which contains the server IP list which is fine, but as far as the database goes I'm pretty sure Minetrack uses SQLite to store data? Is there a way to use an external database like MySQL, or if there's any way at all for the data to be synced across several backend instances?

**Comment by Cryptkeeper** [comment]
It currently only supports sqlite and no external databases, and it's not a priority for me to add it. If someone does by PR, that's a different discussion.

Quite honestly, Minetrack vertically scales pretty easily given its simple purpose and browser heavy focus. minetrack.me runs on a $5/m DigitalOcean droplet serving several hundred concurrent connections without issue, and barely exceeding 3% CPU usage at high peaks. It has in the past seen large floods of traffic (due to live streamers) of over >1.5k without issue. I would be surprised to see someone struggle to see an instance handle over >10k connections on rather mediocre hardware. 

A reverse proxy (like CloudFlare) will help minimize the backend's asset serving (css/js/images) and let it focus purely on pinging and pushing updates.
