### ISSUE TITLE
Use HTTPS

### ISSUE THREAD

**Issue by Techcable** [Cryptkeeper/Minetrack#30]
Its easy to [use https with cloudflare](https://www.cloudflare.com/ssl/)
You can also use [letsencrypt](https://letsencrypt.org/) to encrypt the backend<->cloudflare connection

**Comment by Cryptkeeper** [comment]
I've pushed the traffic back through CloudFlare (previously disabled since they have issues with websockets) and redirected non-HTTPS traffic to HTTPS. It's CloudFlare's flexible SSL so the backend connection isn't encrypted, but can certainly be looked into when I have the time.

If CF proves to be an issue again with the websocket, we'll have to separate put the socket server on a separate subdomain and have it skip CF.
